### ISSUE TITLE
Layour 3 and 4 not working properly on external keyboard

### ISSUE THREAD

**Issue by rggjan** [jgosmann/KE-complex_modifications#1]
To make it work, I had to add the following modifications in "Simple Modifications":

- To get M3 to work: non_us_pound => backslash (\)
- To get Mod4 to work: right_option => right_command
- To get M4 to work: non_us_backslash => right_command

Glad to provide more information or EventViewer logs...

This is a swiss keyboard layout, by the way.

**Comment by LyteFM** [comment]
Same issue here with a German external keyboard. The Simple modifications helped.

**Comment by SirVer** [comment]
@jgosmann The simple modifications make things work for me on my external keyboard too. I did not notice anything immediately missing right now, will report back here if I find something. Thank you very much!

**Comment by jgosmann** [comment]
The general problem is that on external keyboards some key locations or key codes differ (e.g. right_command and right_option are switched around, the same key might send non_us_pound on one keyboard and backslash on another). Not sure what the best way to deal with it is. Potentially, different predefined rules (e.g., “Neo2 layer 3 and 4 keys (Apple keyboard)”, “Neo2 layer 3 and 4 keys (Windows keyboard)” etc.) ... and for less common keyboard types one can manually define the rules.

I also remembered that I have an external German Apple keyboard collecting dust somewhere, so I can test a few things myself.

@LyteFM I cannot reproduce your issue (with an external US american keyboard). Where did you get your keylayout file from? If you are not using [this one] already, you might want to give it a try (it is the one I'm using).

**Comment by LyteFM** [comment]
I'm using your version of the keyboard layout now. Still having problems with those characters, though. I assume it's rather an issue with Karabiner-Elements and my Logitech-Keyboard.

Funnily enough, I'm able to get the "ι", "ϵ", if I release Shift before releasing "i" or "ö". Same applies with releasing Capslock before "w" to get "Ω".

I'm getting some errors in the log:
IOHIDDeviceSetValue error -536850432 for USB Keyboard (device_id:3) @ IOReturn krbn::human_interface_device::set_caps_lock_led_state(krbn::led_state)_block_invoke

**Comment by jgosmann** [comment]
I have been getting the same errors in my log without experiencing the issue, so those are probably unrelated. Can you open Karabiner-EventViewer and post the output you are getting for those specific key combinations?

**Comment by LyteFM** [comment]
Alright, when using the other side for shift + mod4/ mod3 + mod4 I'm getting the expected keys, so no big deal. The Eventviewer-log doesn't even record that the key was pressed, here are some examples:

As a reference, this gives me an „α“:
```
eventType:FlagsChanged    code:0x38       name:left_shift      flags:Shift                              misc:
eventType:FlagsChanged    code:0x3a       name:left_option     flags:Shift Opt                          misc:
eventType:KeyDown         code:0x2        name:d               flags:Shift Opt                          misc:
eventType:KeyUp           code:0x2        name:d               flags:Shift Opt                          misc:
eventType:FlagsChanged    code:0x38       name:left_shift      flags:Opt                                misc:
eventType:FlagsChanged    code:0x3a       name:left_option     flags:                                   misc:
```

This happens when I try to get an „ι“ while pressing left caps and shift:
```
eventType:FlagsChanged    code:0x38       name:left_shift      flags:Shift                              misc:
eventType:FlagsChanged    code:0x3a       name:left_option     flags:Shift Opt                          misc:
eventType:FlagsChanged    code:0x3a       name:left_option     flags:Shift                              misc:
eventType:FlagsChanged    code:0x38       name:left_shift      flags:                                   misc:
```

This happens when I release shift before releasing "i" (i.e. 's' on keyboard):
```
eventType:FlagsChanged    code:0x38       name:left_shift      flags:Shift                              misc:
eventType:FlagsChanged    code:0x3a       name:left_option     flags:Shift Opt                          misc:
eventType:KeyDown         code:0x1        name:s               flags:Shift Opt                          misc:
eventType:FlagsChanged    code:0x38       name:left_shift      flags:Opt                                misc:
eventType:KeyUp           code:0x1        name:s               flags:Opt                                misc:
eventType:FlagsChanged    code:0x3a       name:left_option     flags:                                   misc:
```

With right (Shift and #) it works:
```
eventType:FlagsChanged    code:0x3c       name:right_shift     flags:Shift                              misc:
eventType:FlagsChanged    code:0x3d       name:right_option    flags:Shift Opt                          misc:
eventType:KeyDown         code:0x1        name:s               flags:Shift Opt                          misc:
eventType:KeyUp           code:0x1        name:s               flags:Shift Opt                          misc:
eventType:FlagsChanged    code:0x3d       name:right_option    flags:Shift                              misc:
eventType:FlagsChanged    code:0x3c       name:right_shift     flags:                                   misc:
```

-------

Same problem with „Ω“, left side:
```
eventType:FlagsChanged    code:0x36       name:right_command   flags:Cmd                                misc:
eventType:FlagsChanged    code:0x3a       name:left_option     flags:Opt Cmd                            misc:
eventType:FlagsChanged    code:0x36       name:right_command   flags:Opt                                misc:
eventType:FlagsChanged    code:0x3a       name:left_option     flags:                                   misc:
```
And with release: 
```
eventType:FlagsChanged    code:0x3a       name:left_option     flags:Opt                                misc:
eventType:FlagsChanged    code:0x36       name:right_command   flags:Opt Cmd                            misc:
eventType:FlagsChanged    code:0x38       name:left_shift      flags:Shift Opt Cmd                      misc:
eventType:FlagsChanged    code:0x36       name:right_command   flags:Shift Opt                          misc:
eventType:KeyDown         code:0x6        name:z               flags:Shift Opt                          misc:
eventType:KeyUp           code:0x6        name:z               flags:Shift Opt                          misc:
eventType:KeyDown         code:0x11       name:t               flags:Shift Opt                          misc:
eventType:FlagsChanged    code:0x38       name:left_shift      flags:Opt                                misc:
eventType:FlagsChanged    code:0x3a       name:left_option     flags:                                   misc:
eventType:FlagsChanged    code:0x36       name:right_command   flags:Cmd                                misc:
eventType:KeyUp           code:0x11       name:t               flags:Cmd                                misc:
eventType:FlagsChanged    code:0x36       name:right_command   flags:                                   misc:
```
the right side works:
```
eventType:FlagsChanged    code:0x36       name:right_command   flags:Cmd                                misc:
eventType:FlagsChanged    code:0x3d       name:right_option    flags:Opt Cmd                            misc:
eventType:FlagsChanged    code:0x38       name:left_shift      flags:Shift Opt Cmd                      misc:
eventType:FlagsChanged    code:0x3a       name:left_option     flags:Shift Opt Cmd                      misc:
eventType:FlagsChanged    code:0x3d       name:right_option    flags:Shift Opt Cmd                      misc:
eventType:FlagsChanged    code:0x36       name:right_command   flags:Shift Opt                          misc:
eventType:KeyDown         code:0x6        name:z               flags:Shift Opt                          misc:
eventType:KeyUp           code:0x6        name:z               flags:Shift Opt                          misc:
eventType:KeyDown         code:0x11       name:t               flags:Shift Opt                          misc:
eventType:KeyUp           code:0x11       name:t               flags:Shift Opt                          misc:
eventType:FlagsChanged    code:0x38       name:left_shift      flags:Opt                                misc:
eventType:FlagsChanged    code:0x3a       name:left_option     flags:                                   misc:
eventType:FlagsChanged    code:0x36       name:right_command   flags:Cmd                                misc:
eventType:FlagsChanged    code:0x36       name:right_command   flags:                                   misc:
```
--------

Same issue the other way round. On the left I get „ℚ“:
```
eventType:FlagsChanged    code:0x38       name:left_shift      flags:Shift                              misc:
eventType:FlagsChanged    code:0x3a       name:left_option     flags:Shift Opt                          misc:
eventType:KeyDown         code:0x23       name:p               flags:Shift Opt                          misc:
eventType:KeyUp           code:0x23       name:p               flags:Shift Opt                          misc:
eventType:FlagsChanged    code:0x3a       name:left_option     flags:Shift                              misc:
eventType:FlagsChanged    code:0x38       name:left_shift      flags:                                   misc:
```
But not with strg + #:
```
eventType:FlagsChanged    code:0x36       name:right_command   flags:Cmd                                misc:
eventType:FlagsChanged    code:0x3d       name:right_option    flags:Opt Cmd                            misc:
eventType:FlagsChanged    code:0x3d       name:right_option    flags:Cmd                                misc:
eventType:FlagsChanged    code:0x36       name:right_command   flags:                                   misc:
```

**Comment by jgosmann** [comment]
@rggjan @SirVer I updated the rules to add a rule for Windows-style keyboards.

@LyteFM I think your problem is not with the Neo2 modifications in particular. Either your keyboard does not properly send the keycodes for the pressed keys or it is some bug in Karabiner-Elements itself. I recommend testing those key combinations in the event viewer without the Neo2 rules activated and to report this problem upstream if pressed keys are still missing in the output.

**Comment by rggjan** [comment]
@jgosmann Thanks, just tested the new rules. One issue I still have: The key above the "tab" key (which is used on mac in combination with "command" to switch between windows of the same application, similar to "control-tab" on Windows/Linux) is remapped to "right_command" (according to Karabiner-EventViewer) on Mac. This makes it impossible to set as a keyboard shortcut.

Adding a simple modification like: grave_accent_and_tilde(`) -> period(.) maps it to ".", even with the Complex Modifications enabled, so I can map "command + ." to this shortcut.

Is there any way to remove mapping of this key to right_command? (Which, I think, is also not what the original neo layout indended to do...)

**Comment by jgosmann** [comment]
I updated the rules file, it was still remapping `grave_accent_and_tilde` instead of `non_us_backslash`.

**Comment by rggjan** [comment]
This works, thanks! From my side, it looks like this issue can be closed...
