### ISSUE TITLE
Layer 3 prepends every input with 'U' in vim

### ISSUE THREAD

**Issue by neominik** [jgosmann/KE-complex_modifications#11]
I noticed a strange behaviour today: In vim on the command line, whenever I use a character from the 3rd layer, the input will be prepended with an uppercase 'U'. This is rather annoying for programming, where I use vim and layer 3 all the time.

This is what the event viewer shows me for typing the character '-' (same behaviour with other layer 3 keys, only the last two lines change accordingly):
```
type:key_down        code:226        name:left_option     misc:flags: left_option 
type:key_down        code:225        name:left_shift      misc:flags: left_option,left_shift 
type:key_down        code:4          name:a               misc:flags: left_option,left_shift 
type:key_up          code:4          name:a               misc:flags: left_option,left_shift 
type:key_up          code:225        name:left_shift      misc:flags: left_option 
type:key_up          code:226        name:left_option     misc:
type:key_down        code:15         name:l               misc:
type:key_up          code:15         name:l               misc:
```
For some reason it also emits shift+a, which is (probably correctly) interpreted as the 'U' by vim. Other applications (UI or command line) do not seem to pick up on these key strokes.

My system info: MBP Early '15, macOS 10.15.6 (19G2021), Karabiner Elements 12.10.0, updated neo.keylayout (tried both yours at https://github.com/jgosmann/neo2-layout-osx and the official one), and updated complex modification rules.

**Comment by jgosmann** [comment]
Do you have the "Prevent all layer 3 keys from being treated as option key shortcut" complex rule enabled in Karabiner-Elements? If so, try disabling it. Unfortunately, there are always certain corner cases that cannot be solved for all keys and programs.

However, while I'm getting the same output as you with that complex rule, I do not have any problems in either MacVim or command line vim using iTerm.

**Comment by neominik** [comment]
Thanks for the suggestion. Indeed, when I disable the "Prevent all layer 3 keys…" option, I no longer see the strange behavior. I will observe if the disabled option causes any other problems with keyboard shortcuts, but am closing this issue for now.
