### ISSUE TITLE
Layer4: MacVim - plus not where I expect it.

### ISSUE THREAD

**Issue by SirVer** [jgosmann/KE-complex_modifications#2]
Using Layer4 works for numeric values: 123456789+. To the right of 9 there should be 'plus' - which also works in Firefox and iTerm2. But it does not work in MacVim. This is a long shot, but do you have any idea what that could be?

**Comment by jgosmann** [comment]
I can reproduce the problem, but so far I was not able to fix it. I discovered that some symbols on the keypad are not correctly assigned in the keyboard layout when the Cmd modifier is active. Fixing that, however, did not fix the problem in MacVim. A potential solution might be to map the p key not to keypad_hyphen (which is remapped to + in the keyboard layout), but to M3+n which also produces plus.

**Comment by SirVer** [comment]
Thanks for looking into this! Is there something I can do to help you fix the issue?

**Comment by jgosmann** [comment]
Thanks to @memo33 this should be fixed now. You have to update both the Karabiner Elements complex modifications as well as the keyboard layout file.

**Comment by SirVer** [comment]
@jgosmann @memo33 Can confirm that everything works for me now again! Thank you very much!
