### ISSUE TITLE
Download not possible

### ISSUE THREAD

**Issue by ahmadoh** [jgosmann/KE-complex_modifications#3]
The download of Alternative Keyboard Layouts (e. g. NEO2) is impossible.
The download path 

karabiner://karabiner/assets/complex_modifications/import?url=https%3A%2F%2Fpqrs.org%2Fosx%2Fkarabiner%2Fcomplex_modifications%2Fjson%2Fneo2.json

can’t be opened. The error message says, that the protocol „karabiner://“ is unknown, error code 1000. (See attached file.)

How can I download the layouts I need.

Best regards
![bildschirmfoto 2017-12-01 um 16 21 19](https://user-images.githubusercontent.com/30260362/33490722-5e7de228-d6b8-11e7-94ed-40535978585b.png)

**Comment by jgosmann** [comment]
This is not related to the Neo2 layout, but an upstream issue. [Please report it there.]( https://github.com/pqrs-org/KE-complex_modifications)

It might be a problem with your Karabiner-Elements installation.
