### ISSUE TITLE
Shortcuts like ⌘[ not working properly with NEO

### ISSUE THREAD

**Issue by rggjan** [jgosmann/KE-complex_modifications#4]
Enabling NEO with the keyboard layout + modifications, some shortcuts are not working properly.

For example, typing [ (with M3+L) works as intended. However, trying to use the shortcut ⌘[ doesn't work. When recording the shortcut, it records "⌥+L" instead of ⌘[, making it impossible to use the shortcut ⌘[.

Is there any way this can be fixed?

**Comment by jgosmann** [comment]
This one is tricky because M3 and ⌥ are basically the same key in Neo2. Thus, the keyboard layout can either be configured to map to layer 1 when both ⌘ and ⌥ are pressed which allows for shortcuts like ⌥⌘H. Alternatively, it could be configured to map to layer 3 to allow shortcuts like ⌘[, but then ⌥⌘H could not be used anymore.

**Comment by jgosmann** [comment]
Actually, it might be possible. Can you try out [this keyboard layout file](https://raw.githubusercontent.com/jgosmann/neo2-layout-osx/m3-cmd-shortcuts/neo.keylayout)? Also, what program uses ⌘[ as a shortcut so I could test it myself?

**Comment by rggjan** [comment]
Thanks for the fast response! That shortcut is all over the place, which is why I added the issue in the first place. For example Firefox and Finder use ⌘[ and ⌘] for "Go->Forward", "Go->Back".

I just tried the new file: Interestingly, in "Finder" it seems to work. However, in Firefox it doesn't work (pressing ⌘] is interpreted as ⌥⌘C and opens the inspector). Also in the general mac preferences under Keyboard->Shortcuts it still displays ⌥⌘L when trying to record ⌘[ for a new shortcut.

There is no way to have the option key separate from the M3/Alt key?

**Comment by jgosmann** [comment]
I understand that this behavior is not ideal, but would argue that it is the correct behavior when we compare how the default German keyboard layout shipped with MacOS works. There ⌘[ and ⌘] work in Finder (actual keys ⌥⌘5 and ⌥⌘6), but when assigning a shortcut in system preferences the keys will be interpreted as ⌥⌘5 and ⌥⌘6. In Firefox these shortcuts have no effect at all (interpreted as ⌥⌘5 and ⌥⌘6 which are apparently unassigned), so Firefox is reading out keypresses in a different way than Finder which prevents the fallback to ⌘[ and ⌘] if the actual key combination is unassigned.

I don't think there is any way to make shortcuts work with layer 1 and layer 3 symbols in general. At the moment layer 3 is implemented as the ⌥ layer. One could have the ⌥ layer fixed to layer 1 (to make those shortcuts reliable) and implement layer 3 like layer 4 is implemented. But that implementation is sort of a hack where the key combination M4+symbol triggers multiple key presses: first a dead key switching to the layer 4 symbols and then the actual key. Multiple key presses, however, cannot be assigned as a shortcut (in most applications).

**Comment by rggjan** [comment]
I see... this is unfortunate. Thanks for looking into it anyway, then this seems to be more of a Mac problem in general. I guess the issue can be closed here, then.

Do you know of a way that I could make this work locally just for this use case of ⌘[, for example with a local karabiner modification?

**Comment by jgosmann** [comment]
> Do you know of a way that I could make this work locally just for this use case of ⌘[, for example with a local karabiner modification?

Not in general. You'd need to remap the key combination to some other key combination that has the same effect. In Firefox you can also use ⌘← and ⌘→ to go back and forward. So you could remap ⌥⌘E and ⌥⌘C with a Karabiner complex modification to the other shortcurts. But this will break the shortcut in other application like finder.

**Comment by rggjan** [comment]
Ok, I'll try. Thanks!
