### ISSUE TITLE
Rule 'Neo2 mod 3 and 4 keys' does not work properly

### ISSUE THREAD

**Issue by step4** [jgosmann/KE-complex_modifications#5]
First of all, I have a MacBook with the US Layout.

The mod 3 key on both option keys is working. But capslock does not function as a mod 3 key.

The right command key does not function as the mod 4 key.

I tried to remove and add the rules again, but it does not work either.

**Comment by step4** [comment]
Any news?

**Comment by jgosmann** [comment]
Sorry, I've been somewhat busy and don't really know what the cause of the problem is.
Can you open the Karabiner-EventViewer and check what keycode and name the capslock and right command key produce (with and without the rules)?

**Comment by jgosmann** [comment]
The key codes are the key codes expected without the rules, so the problem isn't that the keyboard is sending weird keycodes. But I still have no idea why the rule isn't working. Do other rules or modification work? Can you manually add simple modifications mapping `caps_lock` to `left_alt`?

**Comment by step4** [comment]
I tried that and figured out that other mappings do not work. But also after uninstalling Karabiner, the capslock does not work the right old way. So I probably try reinstalling the whole mac.

**Comment by jgosmann** [comment]
Did you have any success with the reinstall?

**Comment by step4** [comment]
Sorry I did not use  the neo2 layout anymore since then.
