### ISSUE TITLE
+ in Mod4 

### ISSUE THREAD

**Issue by HuskyNeo** [jgosmann/KE-complex_modifications#7]
Hi, I just installed the rules on my iMac (2017, 10.13.4) and I noticed that I'm not able to make the + Icon in Mod4. I'm using a Windows Keyboard on my Mac and switched the STRG, ALT, WIN and "<" Keys with the simple Modifications inside the Karabiner-Elements App. Everything works (so far) besides the + in Mod4. In Mod3 + it's no problem at all. 

Regards
Husky

**Comment by HuskyNeo** [comment]
ADD: I just noticed that there are a few things mixed up. I checked on the Website of NEO2 and there are a few things in Mod4 that are switched. 
The MOD4...
… / (9) does a *
… * (0) does a - 
… - (ß) does a +
… + (p) does nothing
… – (ü) does a ẞ

That's what I found out for now. Any Ideas? What did I wrong?

**Comment by jgosmann** [comment]
There have been issues with those Mod4 NumPad symbols before. I have to look into the details again, not sure when I will have time to do so. In the meantime, can you let me know from where you installed the keyboard layout file? Did you use the one from [jgosmann/neo2-layout-osx](https://github.com/jgosmann/neo2-layout-osx)? If not can you try out that one? (This is most likely an issue with the keyboard layout file, not with the Karabiner rules.)

**Comment by HuskyNeo** [comment]
Alright, this worked perfectly fine for me. Thanks! Maybe your file should be available on the website!
Thanks a lot.
