### ISSUE TITLE
Mac OS Mojave, Schweizerdeutsche Tastatur, Dollar as Modifier Mod 3 geht nicht

### ISSUE THREAD

**Issue by hanspeter-heeb** [jgosmann/KE-complex_modifications#8]
Im Karabiner Element von \ auf «international 1» umstellen löst das Problem.

War reiner Zufall, gibt es irgendwo ein Mapping für die Keys international 1, 2, 3, etc.?

**Comment by jgosmann** [comment]
Soweit ich weiß handelt es sich bei den Bezeichnungen um die Namen aus der [USB HID Spezifikation](https://www.usb.org/sites/default/files/documents/hut1_12v2.pdf) (siehe Seite 57). Anscheinend sendet die schweizerische Tastatur den Keycode 0x87 (international 1) für die entsprechende Taste, anstelle des Keycodes 0x31 (backslash).
