### ISSUE TITLE
MacOS Mojave, nichts passiert

### ISSUE THREAD

**Issue by Gu108** [jgosmann/KE-complex_modifications#9]
Ich bin exakt der Anleitung unter https://wiki.neo-layout.org/wiki/Neo%20auf%20dem%20Apple%20Macintosh%20einrichten
gefolgt. Die Datei neo.keylayout und neo.icns habe ich Macintosh HD/Library/Keyboard Layouts kopiert.
Auch user/meinName/Keyboard Layouts habe ich testweise versucht. Ohne Erfolg.

Neo2 taucht unter System Preferences/Keyboard/Input sources schlicht nicht auf. Ich kann unter "Input sources" noch auf "+" klicken, auch dort taucht Neo2 weder unter deutsch, englisch oder others auf.
Vermutlich hat das Problem nichts mit der complex modification zu tun, weil bereits die Ebenen 1+2 nicht funktionieren (nicht zur Auswahl auftauchen), ich habe aber Hoffnung, dass ich hier trotzdem Hilfe bekomme.
Ich bin über jeden Hinweis sehr dankbar!

**Comment by Gu108** [comment]
jetzt geht es plötzlich. Ich hatte testweise noch eine Logitech.keylayout installiert. Die hat zuerst auch nicht funktioniert. Dann, ca. 15 Minuten später ist sie plötzlich aufgetaucht. Dann hatte ich testweise ein Australisches Layout installiert und den Rechner neu gestartet. Nach dem Neustart war alles da: Neo, Logitech und australisches Layout...
Keine sinnvolle Erklärung dafür...

**Comment by jgosmann** [comment]
Es kann sein, dass ein Neustart nötig ist, damit die Keyboard Layout-Dateien gefunden werden. Schön, dass es jetzt funktioniert.
